[project]
name = "designai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rami Nguyen", email = "rami.nguyen12@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "crewai>=1.15.20",
    "langchain>=1.4.0",
    "langchain-openai>=1.6.0",
]

[project.scripts]
designai = "designai:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
